---
driver:
  name: ec2
  aws_ssh_key_id: vagrant_insecure
  security_group_ids: ["sg-42e8d62b"]
  region: us-east-2
  availability_zone: us-east-2a
  require_chef_omnibus: true
  subnet_id: "subnet-69b2de00"
  instance_type: t2.micro
  associate_public_ip: true
  interface: dns

provisioner:
  name: chef_solo

transport:
  username: centos
  ssh_key: ~/.ssh/vagrant_insecure

platforms:
  - name: centos7
    driver:
      image_id: ami-18f8df7d

suites:
  - name: default
    run_list:
      - recipe[base::default]
    attributes:
      project:
        aws:
          access_key: <%= ENV['AWS_ACCESS_KEY_ID'] || "AKIAfakekey" %>
          secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] || "notsosecret" %>
