---
driver:
  name: ec2
  aws_ssh_key_id: vagrant_insecure_key
  security_group_ids: ["sg-f1645695"]
  region: ap-southeast-1
  availability_zone: ap-southeast-1a
  require_chef_omnibus: true
  subnet_id: "subnet-12226477"
  instance_type: t2.micro
  associate_public_ip: true
  interface: dns
  image_id: ami-f068a193

provisioner:
  name: chef_solo

transport:
  name: rsync
  username: centos
platforms:
  - name: centos-7
    driver:
      image_id: ami-f068a193

suites:
  - name: default
